num = input('Digite um valor:')
num1 = input('Digite outro valor:')
soma = int(num) + int(num1)
sub = int(num) - int(num1)
div = int(num) / int(num1)
mul = int(num) * int(num1)

print('A soma entre', num, 'e', num1, 'é', soma)
print('A divisão entre', num, 'e', num1, 'é', sub)
print('A divisão entre', num, 'e', num1, 'é', div)
print('A multiplicação entre', num, 'e', num1, 'é', mul)